spring:
  application:
    name: api

  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

springdoc:
  packages-to-scan: med.salus.api

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET}